### PR TITLE
27-3-ADA

### PR DESCRIPTION
**Pull request by drs-11**

### CODE REVIEW

**Comment by sarthakgupta072** [comment]
wrong title format!

**Comment by drs-11** [comment]
done

**Comment by sarthakgupta072** [comment]
> done

Still wrong. See the task description carefully.

**Comment by drs-11** [comment]
now?

**Review by sarthakgupta072 — CHANGES_REQUESTED** [review]
Arrange according to S.No. Wrong order.

**Review by sarthakgupta072 — APPROVED** [review]
Cool! Merging

**Pull request merged**
