### PR TITLE
40-5-indian5230

### PR DESCRIPTION
**Pull request by Rohit-5230**
update by "indian5230" .

### CODE REVIEW

**Comment by sarthakgupta072** [comment]
Wrong pull request title.

**Comment by Rohit-5230** [comment]
> Wrong pull request title.
 check it again. hum excel sheet dekhe hi nhi the bhaiya.

**Comment by sarthakgupta072** [comment]
Pull Request **Title**. Read the task description carefully.

**Comment by Rohit-5230** [comment]
> Pull Request **Title**. Read the task description carefully.

kar diye bhaiya.

**Review by sarthakgupta072 — APPROVED** [review]

**Pull request merged**
